/**
 * Rendering a profile into files, and the plan that describes doing so.
 *
 * The plan is the unit, not the write. `init` builds a complete plan, prints
 * it, and only then applies it — so `--dry-run` is the same code path minus
 * the final step, and cannot drift from the real one. A dry run that runs
 * different code is a dry run that lies.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import type { Profile } from "./profiles";

export type Disposition =
  /** The file does not exist; it will be created. */
  | "create"
  /** The file exists with different content; it will be rewritten. */
  | "update"
  /** The file exists and already matches; nothing to do. */
  | "unchanged"
  /** The kit will not touch this file, and says why. */
  | "skip";

export interface PlannedFile {
  path: string;
  disposition: Disposition;
  contents: string | null;
  reason: string;
}

export interface Plan {
  profile: string;
  root: string;
  files: PlannedFile[];
  manualSteps: string[];
  notes: string[];
}

/** Two trailing-newline-tolerant strings, compared as file content. */
function sameContent(a: string, b: string): boolean {
  return a.replace(/\s+$/, "") === b.replace(/\s+$/, "");
}

function planFile(
  root: string,
  path: string,
  contents: string,
  reason: string,
): PlannedFile {
  const absolute = join(root, path);
  if (!existsSync(absolute)) {
    return { path, disposition: "create", contents, reason };
  }
  let existing: string;
  try {
    existing = readFileSync(absolute, "utf8");
  } catch {
    return {
      path,
      disposition: "skip",
      contents: null,
      reason: "exists but could not be read — left alone rather than clobbered",
    };
  }
  if (sameContent(existing, contents)) {
    return { path, disposition: "unchanged", contents, reason };
  }
  return { path, disposition: "update", contents, reason };
}

export function renderConfig(profile: Profile): string {
  // configVersion is written from the start. The kernel reserves it and
  // ignores it; emitting it now means a future schema bump has something to
  // hinge on in repos initialised today.
  const config: Record<string, unknown> = {
    configVersion: 1,
    docs: profile.docs,
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

export function renderKitConfig(profile: Profile, kitVersion: string): string {
  // Kit settings live here rather than in nullius.config.json, whose unknown
  // keys are a hard error: a kit key there breaks every older pinned kernel.
  const config = {
    kitVersion,
    profile: profile.name,
    requireMarkers: profile.requireMarkers,
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

export function renderWorkflow(profile: Profile, actionRef: string): string {
  const globs = profile.docs.map((glob) => `"${glob}"`).join(" ");
  const requireMarkers = profile.requireMarkers ? "\n          require-markers: true" : "";
  return `# .github/workflows/claims.yml — generated by \`nullius-kit init\`.
# Re-render with \`nullius-kit doctor --fix\`; edits here are overwritten.
name: claims
on: pull_request
permissions:
  contents: read
  pull-requests: write
jobs:
  claims:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # \`git show <rev>:<path>\` needs the commit an anchor names. Without
          # this, every rev-stamped anchor degrades to the advisory
          # UNVERIFIABLE-REV and the gate silently stops gating.
          fetch-depth: 0
      - uses: ${actionRef}
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
          globs: ${globs}${requireMarkers}
`;
}

export interface PlanOptions {
  root: string;
  profile: Profile;
  kitVersion: string;
  actionRef: string;
  /** From `mayWriteHooks` — carried so the plan can explain the omission. */
  hookPolicy: { allowed: boolean; reason: string };
}

export function buildPlan(options: PlanOptions): Plan {
  const { root, profile, kitVersion, actionRef, hookPolicy } = options;
  const files: PlannedFile[] = [];
  const notes: string[] = [];

  for (const artifact of profile.artifacts) {
    if (artifact.path === "nullius.config.json") {
      files.push(planFile(root, artifact.path, renderConfig(profile), artifact.reason));
    } else if (artifact.path === ".nullius/kit.json") {
      files.push(
        planFile(root, artifact.path, renderKitConfig(profile, kitVersion), artifact.reason),
      );
    } else if (artifact.path === ".github/workflows/claims.yml") {
      files.push(
        planFile(root, artifact.path, renderWorkflow(profile, actionRef), artifact.reason),
      );
    }
  }

  // Stated as a fact in the plan, not silently omitted. An installer that
  // quietly declines to do something is indistinguishable from one that forgot.
  if (!hookPolicy.allowed) {
    notes.push(`No hook entries written: ${hookPolicy.reason}.`);
  }

  return { profile: profile.name, root, files, manualSteps: [...profile.manualSteps], notes };
}

export interface ApplyResult {
  written: string[];
  unchanged: string[];
  skipped: string[];
}

/** Applies a plan. `--dry-run` simply does not call this. */
export function applyPlan(plan: Plan): ApplyResult {
  const result: ApplyResult = { written: [], unchanged: [], skipped: [] };

  for (const file of plan.files) {
    if (file.disposition === "unchanged") {
      result.unchanged.push(file.path);
      continue;
    }
    if (file.disposition === "skip" || file.contents === null) {
      result.skipped.push(file.path);
      continue;
    }
    const absolute = join(plan.root, file.path);
    mkdirSync(dirname(absolute), { recursive: true });
    writeFileSync(absolute, file.contents, "utf8");
    result.written.push(file.path);
  }

  return result;
}

/** The printed record. Every path, what happened to it, and why. */
export function formatPlan(plan: Plan, dryRun: boolean): string {
  const lines: string[] = [];
  lines.push(
    dryRun
      ? `Plan for profile \`${plan.profile}\` — DRY RUN, nothing will be written.`
      : `Applying profile \`${plan.profile}\`.`,
  );
  lines.push("");

  if (plan.files.length === 0) {
    lines.push("  (no files for this profile)");
  }
  for (const file of plan.files) {
    lines.push(`  ${file.disposition.padEnd(9)} ${file.path}`);
    lines.push(`            ${file.reason}`);
  }

  for (const note of plan.notes) {
    lines.push("");
    lines.push(`  note: ${note}`);
  }

  if (plan.manualSteps.length > 0) {
    lines.push("");
    lines.push("  Steps this tool will not do for you:");
    for (const step of plan.manualSteps) lines.push(`    - ${step}`);
  }

  return lines.join("\n");
}
